const colors = { project: "#70ddb4", architecture: "#66b5ee", policy: "#efbf6c", security: "#ef716c", agent: "#b89bf2", evidence: "#f197c5", knowledge: "#aab7b2" };
const labels = { project: "Projeto", architecture: "Arquitetura", policy: "Políticas", security: "Segurança", agent: "Agentes", evidence: "Evidências", knowledge: "Conhecimento" };
const canvas = document.querySelector("#graph");
const ctx = canvas.getContext("2d");
const state = { nodes: [], edges: [], visible: [], groups: new Set(Object.keys(colors)), scale: 1, offsetX: 0, offsetY: 0, dragging: false, selected: null, query: "" };

function resize() { const rect=canvas.getBoundingClientRect(); const dpr=Math.min(devicePixelRatio,2); canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);draw(); }
function seededPosition(id,index,total){ let hash=2166136261;for(const char of id){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619)}const angle=(index/total)*Math.PI*2+(hash%100)/70;const radius=80+Math.sqrt(index/total)*Math.min(canvas.clientWidth,canvas.clientHeight)*.38;return{x:Math.cos(angle)*radius+(hash%47),y:Math.sin(angle)*radius+((hash>>>8)%47)} }
function setVisible(){ const q=state.query.toLocaleLowerCase("pt-BR");state.visible=state.nodes.filter(n=>state.groups.has(n.group)&&(!q||`${n.label} ${n.path} ${n.summary}`.toLocaleLowerCase("pt-BR").includes(q)));state.visibleIds=new Set(state.visible.map(n=>n.id));document.querySelector("#empty-state").hidden=state.visible.length>0;updateStats();updateResults();draw(); }
function updateStats(){const edges=state.edges.filter(e=>state.visibleIds?.has(e.source)&&state.visibleIds?.has(e.target)).length;document.querySelector("#graph-stats").textContent=`${state.visible.length} nós · ${edges} relações · projeção somente leitura`;}
function updateResults(){const list=document.querySelector("#result-list");list.replaceChildren();for(const node of state.visible.slice(0,14)){const button=document.createElement("button");button.className="result";button.innerHTML=`<i style="background:${colors[node.group]}"></i><span></span>`;button.querySelector("span").textContent=node.label;button.onclick=()=>selectNode(node);list.append(button)}if(!list.children.length){const empty=document.createElement("div");empty.className="result-list-empty";empty.textContent="Nenhum resultado.";list.append(empty)}}
function draw(){if(!state.nodes.length)return;const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(w/2+state.offsetX,h/2+state.offsetY);ctx.scale(state.scale,state.scale);const ids=state.visibleIds||new Set();ctx.lineWidth=.55/state.scale;for(const edge of state.edges){if(!ids.has(edge.source)||!ids.has(edge.target))continue;const a=state.nodeMap.get(edge.source),b=state.nodeMap.get(edge.target);ctx.strokeStyle="rgba(141,163,156,.26)";ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}for(const node of state.visible){const selected=node===state.selected;const radius=(node.type==="document"?6.5:node.type==="concept"?4:2.7)*(selected?1.45:1);ctx.shadowColor=colors[node.group];ctx.shadowBlur=selected?18:node.type==="document"?7:2;ctx.fillStyle=colors[node.group];ctx.globalAlpha=node.type==="detail"?.62:1;ctx.beginPath();ctx.arc(node.x,node.y,radius,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;if(selected||state.scale>1.65&&node.type==="document"){ctx.shadowBlur=0;ctx.fillStyle="#e9f1ed";ctx.font=`${10/state.scale}px system-ui`;ctx.fillText(node.label,node.x+10/state.scale,node.y+3/state.scale)}}ctx.restore()}
function selectNode(node){state.selected=node;document.querySelector("#details").classList.add("open");const related=state.edges.filter(e=>e.source===node.id||e.target===node.id).length;const content=document.querySelector("#details-content");content.replaceChildren();const eyebrow=document.createElement("span");eyebrow.className="eyebrow";eyebrow.textContent=labels[node.group];const title=document.createElement("h2");title.textContent=node.label;const summary=document.createElement("p");summary.textContent=node.summary;const meta=document.createElement("div");meta.className="meta";meta.innerHTML=`<div><small>Tipo</small><strong>${node.type}</strong></div><div><small>Relações</small><strong>${related}</strong></div><div><small>Estado</small><strong>${node.status}</strong></div><div><small>Fonte</small><strong>repositório</strong></div>`;const source=document.createElement("div");source.className="source-path";source.textContent=node.path;content.append(eyebrow,title,summary,meta,source);draw()}
function screenNode(event){const rect=canvas.getBoundingClientRect(),x=(event.clientX-rect.left-canvas.clientWidth/2-state.offsetX)/state.scale,y=(event.clientY-rect.top-canvas.clientHeight/2-state.offsetY)/state.scale;let match=null,distance=14/state.scale;for(const node of state.visible){const d=Math.hypot(node.x-x,node.y-y);if(d<distance){distance=d;match=node}}return match}
function zoom(factor){state.scale=Math.max(.45,Math.min(3.2,state.scale*factor));draw()}

async function init(){const response=await fetch("data/knowledge-graph.json");if(!response.ok)throw new Error("Não foi possível carregar a projeção.");const data=await response.json();state.nodes=data.nodes;state.edges=data.edges;state.nodeMap=new Map(state.nodes.map((node,index)=>[node.id,Object.assign(node,seededPosition(node.id,index,state.nodes.length))]));document.querySelector("#source-count").textContent=`${data.source_count} fontes · ${data.integrity.slice(0,7)}`;document.querySelector("#legend").innerHTML=Object.entries(labels).map(([key,label])=>`<span><i style="background:${colors[key]}"></i>${label}</span>`).join("");document.querySelector("#filter-list").innerHTML=Object.entries(labels).map(([key,label])=>`<label class="filter"><input type="checkbox" value="${key}" checked><i class="swatch" style="color:${colors[key]};background:${colors[key]}"></i>${label}</label>`).join("");document.querySelector("#folders").innerHTML=[['◫','00 — Visão geral'],['◇','01 — Projeto Maestro'],['⌁','02 — Arquitetura'],['✓','20 — Políticas e segurança'],['◎','99 — Sistema']].map(([icon,label],i)=>`<button class="folder ${i===0?'active':''}"><span>${icon}</span><b>${label}</b><small>${i?Math.max(1,Math.floor(data.nodes.length/(i+2))):data.nodes.length}</small></button>`).join("");setVisible();resize();}
document.querySelector("#search").addEventListener("input",e=>{state.query=e.target.value;setVisible()});document.querySelector("#filter-list").addEventListener("change",e=>{e.target.checked?state.groups.add(e.target.value):state.groups.delete(e.target.value);setVisible()});
document.querySelector("#zoom-in").onclick=()=>zoom(1.2);document.querySelector("#zoom-out").onclick=()=>zoom(.82);document.querySelector("#reset-view").onclick=()=>{state.scale=1;state.offsetX=state.offsetY=0;draw()};document.querySelector("#close-details").onclick=()=>document.querySelector("#details").classList.remove("open");
canvas.addEventListener("wheel",e=>{e.preventDefault();zoom(e.deltaY<0?1.1:.9)},{passive:false});canvas.addEventListener("pointerdown",e=>{state.dragging=true;state.lastX=e.clientX;state.lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener("pointermove",e=>{if(!state.dragging)return;state.offsetX+=e.clientX-state.lastX;state.offsetY+=e.clientY-state.lastY;state.lastX=e.clientX;state.lastY=e.clientY;draw()});canvas.addEventListener("pointerup",e=>{const moved=Math.hypot(e.clientX-state.lastX,e.clientY-state.lastY);state.dragging=false;if(moved<4){const node=screenNode(e);if(node)selectNode(node)}});window.addEventListener("resize",resize);
init().catch(error=>{document.querySelector("#empty-state").hidden=false;document.querySelector("#empty-state").textContent=error.message});
